---
groups:
- name: syslog-release
  jobs:
  - deploy-cf-with-created-syslog
  - cf-acceptance-tests
  - delete-cf-deployment
  - create-final-release
- name: infrastructure
  jobs:
  - setup-infrastructure
  - destroy-infrastructure

resources:
# Manifests and Releases
- name: syslog-release
  type: git
  source:
    branch: develop
    private_key: ((syslog_release_read_write_deploy_key))
    uri: git@github.com:cloudfoundry/syslog-release.git
- name: syslog-release-master
  type: git
  source:
    branch: master
    private_key: ((syslog_release_read_write_deploy_key))
    uri: git@github.com:cloudfoundry/syslog-release.git
- name: cf-deployment-master
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment.git
- name: cf-acceptance-tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git
- name: cats-concourse-task
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cats-concourse-task.git

# ENV
- name: tycho-env-bbl-state
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/tycho-env.git
    private_key: ((tycho_env_git_deploy_key))
    paths:
    - bbl-state.json
    - google_account_creds.json
- name: tycho-env-vars-store
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/tycho-env.git
    private_key: ((tycho_env_git_deploy_key))
    paths:
    - deployment-vars.yml
- name: tycho-env-integration-configs
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/tycho-env.git
    private_key: ((tycho_env_git_deploy_key))
    paths:
    - cats_integration_config.json

# Control
- name: weekly
  type: time
  source:
    interval: 168h
    location: US/Pacific
    start: 9:00 AM
    stop: 10:00 AM
    days: [Tuesday]

# Concourse Tasks
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
    tag_filter: v4.*
- name: runtime-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git

jobs:
- name: setup-infrastructure
  serial_groups: [tycho]
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: tycho-env-bbl-state
  - task: setup-infrastructure
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: google_account_creds.json
      BBL_GCP_PROJECT_ID: ((tycho_gcp_project))
      BBL_GCP_REGION: us-central1
      BBL_GCP_ZONE: us-central1-a
      BBL_LB_CERT: ((tycho_cf_ssl_cert))
      BBL_LB_KEY: ((tycho_cf_ssl_cert_private_key))
      LB_DOMAIN: tycho.cf-app.com
      BBL_ENV_NAME: tycho
    input_mapping:
      bbl-state: tycho-env-bbl-state
      ops-files: tycho-env-bbl-state
    ensure:
      put: tycho-env-bbl-state
      params:
        repository: updated-bbl-state
        rebase: true

- name: destroy-infrastructure
  serial_groups: [tycho]
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: tycho-env-bbl-state
    - get: cf-deployment-concourse-tasks
  - task: destroy-infrastructure
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    input_mapping:
      bbl-state: tycho-env-bbl-state
    ensure:
      put: tycho-env-bbl-state
      params:
        repository: updated-bbl-state
        rebase: true

- name: deploy-cf-with-created-syslog
  serial_groups: [tycho]
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: cf-deployment-master
    - get: tycho-env-bbl-state
      trigger: true
      passed: [smoke-tests]
    - get: tycho-env-vars-store
    - get: tycho-env-integration-configs
    - get: syslog-release
      trigger: true
      passed: [smoke-tests]
    - get: weekly
      trigger: true
      passed: [smoke-tests]
  - task: upload-stemcell
    file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
    input_mapping:
      bbl-state: tycho-env-bbl-state
      cf-deployment: cf-deployment-master
  - task: deploy-cf-with-created-syslog
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    input_mapping:
      bbl-state: tycho-env-bbl-state
      cf-deployment: cf-deployment-master
      release: syslog-release
      ops-files: cf-deployment-master
      vars-store: tycho-env-vars-store
      vars-files: tycho-env-vars-store
    params:
      SYSTEM_DOMAIN: tycho.cf-app.com
    ensure:
      put: tycho-env-vars-store
      params:
        repository: updated-vars-store
        rebase: true
  - task: update-integration-configs
    file: cf-deployment-concourse-tasks/update-integration-configs/task.yml
    input_mapping:
      vars-store: tycho-env-vars-store
      integration-configs: tycho-env-integration-configs
    ensure:
      put: tycho-env-integration-configs
      params:
        repository: updated-integration-configs
        rebase: true
  - task: run-bosh-cleanup
    file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
    input_mapping:
      bbl-state: tycho-env-bbl-state

- name: cf-acceptance-tests
  serial_groups: [tycho]
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: cats-concourse-task
    - get: cf-acceptance-tests
    - get: cf-deployment-master
      passed: [deploy-cf-with-created-syslog]
    - get: tycho-env-bbl-state
      trigger: true
      passed: [deploy-cf-with-created-syslog]
    - get: tycho-env-vars-store
      passed: [deploy-cf-with-created-syslog]
    - get: tycho-env-integration-configs
    - get: cf-deployment-concourse-tasks
    - get: syslog-release
      passed: [deploy-cf-with-created-syslog]
      trigger: true
    - get: weekly
      trigger: true
      passed: [deploy-cf-with-created-syslog]
  - task: set-cats-feature-flags
    file: cf-deployment-concourse-tasks/set-feature-flags/task.yml
    input_mapping:
      vars-store: tycho-env-vars-store
    params:
      SYSTEM_DOMAIN: tycho.cf-app.com
  - task: run-cats
    input_mapping:
      integration-config: tycho-env-integration-configs
    file: cats-concourse-task/task.yml
    params:
      CONFIG_FILE_PATH: cats_integration_config.json

- name: delete-cf-deployment
  public: true
  serial_groups: [tycho]
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
    - get: cf-deployment-concourse-tasks
    - get: tycho-env-bbl-state
      trigger: true
      passed: [cf-acceptance-tests]
    - get: syslog-release
      trigger: true
      passed: [cf-acceptance-tests]
    - get: weekly
      trigger: true
      passed: [cf-acceptance-tests]
  - task: delete-cf-deployment
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    input_mapping:
      bbl-state: tycho-env-bbl-state

- name: create-final-release
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
    - get: syslog-release
      passed: [cf-acceptance-tests]
      trigger: true
    - get: syslog-release-master
  - task: create-final-release
    file: runtime-ci/scripts/ci/create-final-release/task.yml
    input_mapping:
      release-repo-master: syslog-release-master
      release-repo: syslog-release
    params:
      RELEASE_NAME: syslog
      BLOBS_BUCKET_ACCESS_KEY_ID: ((syslog_release_blobs_buckets_access_key_id))
      BLOBS_BUCKET_SECRET_KEY: ((syslog_release_blobs_buckets_secret_access_key))
  - put: syslog-release-master
    params:
      repository: final-release-repo
      tag: final-release-repo/version_number
      tag_prefix: v
  - task: merge-master-into-develop
    file: runtime-ci/scripts/ci/merge-master-into-develop/task.yml
    input_mapping:
      release-repo-master: syslog-release-master
      release-repo: syslog-release
  - put: syslog-release
    params:
      repository: final-release-repo
