---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: syslog-ci
- name: release-repo
- name: release-version

outputs:
  - name: final-release-repo

run:
  path: syslog-ci/tasks/create-final-release/task

params:
  BLOBS_BUCKET_ACCESS_KEY_ID:
  BLOBS_BUCKET_SECRET_KEY:
